theme: minima
title: LLM Application-Architecture Design
description: The AI Architect's Field Manual
baseurl: "/LLM-App-Desing"
url: "https://memari-majid.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 