theme: jekyll-theme-cayman
title: LLM Application-Architecture Design
description: The AI Architect's Field Manual
baseurl: ""
url: "https://memari-majid.github.io"
github_username: memari-majid
repository: memari-majid/LLM-Review

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/ 