site_name: AI Application Architecture Design
site_url: https://memari-majid.github.io/AI-Application-Architecture-Design/
site_description: Your guide to designing production-ready AI applications.
repo_url: https://github.com/memari-majid/AI-Application-Architecture-Design
repo_name: memari-majid/AI-Application-Architecture-Design

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.integrate
  palette:
    scheme: default
    primary: indigo
    accent: indigo

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# Navigation will now be primarily sidebar-driven
# The first item is still the effective homepage
nav:
  - Introduction: chapters/00-introduction.md
  - Stakeholder Alignment: chapters/01-stakeholder-alignment.md
  - Model Selection: chapters/02-llm-model-selection.md
  - RAG Architecture: chapters/03-rag-architecture.md
  - Agent Architectures: chapters/04-agent-architectures.md
