site_name: AI Application Architecture Design
site_url: https://memari-majid.github.io/LLM-App-Design/
site_description: Your guide to designing production-ready AI applications.
repo_url: https://github.com/memari-majid/LLM-App-Design
repo_name: memari-majid/LLM-App-Design

theme:
  name: material
  features:
    - navigation.tabs # Keep this off for no top tabs
    - navigation.sections # This will create sections in the sidebar based on nav structure
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - toc.integrate
  palette:
    scheme: default
    primary: indigo
    accent: indigo

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# Navigation will now be primarily sidebar-driven
# The first item is still the effective homepage
nav:
  - Home: chapters/00-introduction.md # This will be the site's homepage
  - Stakeholder Alignment: chapters/01-stakeholder-alignment.md
  - Model Selection: chapters/02-llm-model-selection.md
  - RAG Architecture: chapters/03-rag-architecture.md
  - Agent Architectures: chapters/04-agent-architectures.md
  - Overview: index.md # The former landing page, now an "Overview" page
  - About: about.md
